TRUNCATE TABLE account_balances,
account_transactions,
client_profiles,
contract_clients,
contract_contractors,
contractor_profiles,
contracts,
dispute_evidence,
disputes,
milestones,
notifications,
payments,
reviews,
session,
status_history,
subscriptions,
verification RESTART IDENTITY CASCADE;